In [9]:
import os
import pandas as pd

# Define the directory containing the xlsx files
directory = r'C:\Heri\GitHub\.Semester\Data-Mining\03-Tasas-de-Interes-al-Consumo\Datos\Series'
directory2 = r'C:\Heri\GitHub\.Semester\Data-Mining\03-Tasas-de-Interes-al-Consumo\Datos\Series-csv'

# Iterate over all files in the directory
for filename in os.listdir(directory):
    file_path = os.path.join(directory, filename) 
    
    # Read the xlsx file
    df = pd.read_excel(file_path)
    
    # Construct the csv file path
    csv_file_path = os.path.join(directory2, filename.replace('.xlsx', '.csv'))
    
    # Save the dataframe to csv
    df.to_csv(csv_file_path, index=False)

c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [10]:
tiie = pd.read_csv(r'C:\Heri\GitHub\.Semester\Data-Mining\03-Tasas-de-Interes-al-Consumo\Datos\Series-csv\01-Tasa-de-Interes-Interbancaria.csv')
tiie.head(20)

,Banco de México,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,Tasas y precios de referencia,NaN,NaN,NaN,NaN,NaN
2,Tasas de Interés Interbancarias,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,Fecha de consulta: 22/02/2025 04:42:21,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,Título,"TIIE de Fondeo a Un Día Hábil Bancario, Median...","TIIE a 28 días, Tasa de interés en por ciento ...",Tasas de interés interbancarias Por ciento anu...,TIIE a 182 días,Tasas de interés interbancarias Por ciento anu...
9,Periodo disponible,02/01/2006 - 21/02/2025,23/03/1995 - 24/02/2025,23/01/1997 - 24/02/2025,06/04/2011 - 24/02/2025,21/01/1993 - 31/01/2002
10,Periodicidad,Diaria,Diaria,Diaria,Diaria,Diaria
11,Cifra,Tasas Promedio,Porcentajes,Porcentajes,Porcentajes,Porcentajes
12,Unidad,Porcentajes,Sin Unidad,Porcentajes,Porcentajes,Porcentajes
13,Base,NaN,NaN,NaN,NaN,NaN
14,Aviso,NaN,NaN,NaN,NaN,NaN
15,Tipo de información,Niveles,Niveles,Niveles,Niveles,Niveles
16,Fecha,SF331451,SF43783,SF43878,SF111916,SF43947
17,2006-01-02 00:00:00,8.27,8.57,N/E,N/E,N/E
18,2006-01-03 00:00:00,8.28,8.565,N/E,N/E,N/E
19,2006-01-04 00:00:00,8.28,8.55,N/E,N/E,N/E

In [11]:
tiiexlsx = pd.read_excel(r'C:\Heri\GitHub\.Semester\Data-Mining\03-Tasas-de-Interes-al-Consumo\Datos\Series\01-Tasa-de-Interes-Interbancaria.xlsx')
tiiexlsx.head(20)

c:\Users\herie\.conda\envs\GDA\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Banco de México,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,Tasas y precios de referencia,NaN,NaN,NaN,NaN,NaN
2,Tasas de Interés Interbancarias,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,Fecha de consulta: 22/02/2025 04:42:21,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,Título,"TIIE de Fondeo a Un Día Hábil Bancario, Median...","TIIE a 28 días, Tasa de interés en por ciento ...",Tasas de interés interbancarias Por ciento anu...,TIIE a 182 días,Tasas de interés interbancarias Por ciento anu...
9,Periodo disponible,02/01/2006 - 21/02/2025,23/03/1995 - 24/02/2025,23/01/1997 - 24/02/2025,06/04/2011 - 24/02/2025,21/01/1993 - 31/01/2002
10,Periodicidad,Diaria,Diaria,Diaria,Diaria,Diaria
11,Cifra,Tasas Promedio,Porcentajes,Porcentajes,Porcentajes,Porcentajes
12,Unidad,Porcentajes,Sin Unidad,Porcentajes,Porcentajes,Porcentajes
13,Base,NaN,NaN,NaN,NaN,NaN
14,Aviso,NaN,NaN,NaN,NaN,NaN
15,Tipo de información,Niveles,Niveles,Niveles,Niveles,Niveles
16,Fecha,SF331451,SF43783,SF43878,SF111916,SF43947
17,2006-01-02 00:00:00,8.27,8.57,N/E,N/E,N/E
18,2006-01-03 00:00:00,8.28,8.565,N/E,N/E,N/E
19,2006-01-04 00:00:00,8.28,8.55,N/E,N/E,N/E